
#' test
#'
#' master table as created by exel makro
#'
#' @format A data frame with 114 rows and 6 variables:
#' \describe{
#'   \item{\code{V1}}{integer. number of rings.}
#'   \item{\code{V2}}{double. ring width in µm.}
#'   \item{\code{V3}}{double. hatchcheck in µm.}
#'   \item{\code{V4}}{double. radius of the otolith in µm.}
#'   \item{\code{V5}}{integer. age of the fish in days.}
#'   \item{\code{V6}}{integer. id}
#' }
"test"


#' makro output
#'
#' output as created by ototools
#'
#' @format A data frame with 1 rows and 6 variables:
#' \describe{
#'   \item{\code{id}}{character. id}
#'   \item{\code{ring_no}}{list. number of rings.}
#'   \item{\code{ring_width}}{list. ring width in µm.}
#'   \item{\code{hc}}{double. hatchcheck in µm.}
#'   \item{\code{oto_rad}}{double. radius of the otolith in µm.}
#'   \item{\code{age}}{double. age of the fish in days.}
#' }
"makro_output"


#' dat
#'
#' data generated by myself
#'
#' @format A data frame with 50 rows and 28 variables:
#' \describe{
#'   \item{\code{id}}{character. id.}
#'   \item{\code{ring_no}}{list. number of rings.}
#'   \item{\code{ring_width}}{list. ring width in µm.}
#'   \item{\code{hc}}{double. hatchcheck in µm.}
#'   \item{\code{oto_rad}}{double. radius of the otolith in µm.}
#'   \item{\code{age}}{double. age of the fish in days.}
#'   \item{\code{sampling}}{character. sampling instrument.}
#'   \item{\code{haul}}{character. number of haul.}
#'   \item{\code{catchday}}{integer. day of catch.}
#'   \item{\code{catch_date}}{character. date of catch.}
#'   \item{\code{tl_mm}}{integer. total length fish in mm.}
#'   \item{\code{sl_mm}}{integer. standard length fish in mm.}
#'   \item{\code{wet_weight_g}}{double. wet weight fish in g.}
#'   \item{\code{dry_weight.schale}}{double. dry weight fish + dish in g.}
#'   \item{\code{weight_schale}}{double. weight dish in g.}
#'   \item{\code{dry_weight_g}}{double. dry weight fish in g.}
#'   \item{\code{oto_1.2}}{integer. first or second otolith of fish x.}
#'   \item{\code{oto_weight_mg}}{double. otolith weight in mg.}
#'   \item{\code{oto_diameter_mm}}{double. otolith diameter in mm.}
#'   \item{\code{foto}}{character. are fotos aviable? y = yes, n = no.}
#'   \item{\code{quality}}{double. quality of the fotos. 1 = good, 4 = bad.}
#'   \item{\code{first_change}}{integer. first change in increment width at ring x.}
#'   \item{\code{sec_change_}}{integer. second change in increment width at ring y.}
#'   \item{\code{comment}}{character. comments.}
#'   \item{\code{julday}}{list. julian day of increment formation.}
#'   \item{\code{move_ave}}{list. see huessy 2003.}
#'   \item{\code{cum_oto_rad}}{list. otolith radius at increment x.}
#' }
"dat"


#' basic
#'
#' some basic data for all fish
#'
#' @format A data frame with 50 rows and 22 variables:
#' \describe{
#'   \item{\code{sampling}}{character. sampling instrument.}
#'   \item{\code{haul}}{character. number of haul.}
#'   \item{\code{catchday}}{integer. day of catch.}
#'   \item{\code{catch_date}}{character. date of catch.}
#'   \item{\code{id}}{character. id.}
#'   \item{\code{tl_mm}}{integer. total length fish in mm.}
#'   \item{\code{sl_mm}}{integer. standard length fish in mm.}
#'   \item{\code{wet_weight_g}}{double. wet weight fish in g.}
#'   \item{\code{dry_weight.schale}}{double. dry weight fish + dish in g.}
#'   \item{\code{weight_schale}}{double. weight dish in g.}
#'   \item{\code{dry_weight_g}}{double. dry weight fish in g.}
#'   \item{\code{oto_1.2}}{integer. first or second otolith of fish x.}
#'   \item{\code{oto_weight_mg}}{double. otolith weight in mg.}
#'   \item{\code{oto_diameter_mm}}{double. otolith diameter in mm.}
#'   \item{\code{foto}}{character. are fotos aviable? y = yes, n = no.}
#'   \item{\code{age}}{double. age of the fish in days.}
#'   \item{\code{quality}}{double. quality of the fotos. 1 = good, 4 = bad.}
#'   \item{\code{first_change}}{integer. first change in increment width at ring x.}
#'   \item{\code{sec_change_}}{integer. second change in increment width at ring y.}
#'   \item{\code{comment}}{character. comments.}
#' }
"basic"


#' example
#'
#' exel output generated by imagePRO for fish 708
#'
#' @format A data frame with 123 rows and 18 variables:
#' \describe{
#'   \item{\code{V1}}{integer. increasing numbers from 1 on.}
#'   \item{\code{V2}}{integer. same as X.}
#'   \item{\code{V3}}{integer. x coordinates on the foto.}
#'   \item{\code{V4}}{integer. y coordinates on the foto.}
#'   \item{\code{V5}}{integer. not relevant.}
#'   \item{\code{V6}}{integer. not relevant.}
#'   \item{\code{V7}}{integer. not relevant.}
#'   \item{\code{V8}}{integer. not relevant.}
#'   \item{\code{V9}}{integer. not relevant.}
#'   \item{\code{V10}}{integer. not relevant.}
#'   \item{\code{V11}}{integer. not relevant.}
#'   \item{\code{V12}}{integer. not relevant.}
#'   \item{\code{V13}}{integer. not relevant.}
#'   \item{\code{V14}}{integer. not relevant.}
#'   \item{\code{V15}}{integer. not relevant.}
#'   \item{\code{V16}}{integer. not relevant.}
#'   \item{\code{V17}}{integer. not relevant.}
#'   \item{\code{V18}}{integer. not relevant.}
#' }
"example"
